### ISSUE TITLE
How to get dataset image files?

### ISSUE THREAD

**Issue by TIB-Visual-Analytics** [Ekraam/MEIR#1]
Thank you for sharing the dataset. Unfortunately, it is not possible to download the images from Flickr having only the photo ID in myopinion? According to https://www.flickr.com/services/api/misc.urls.html further data are required to construct the download link or am I missing something?

**Comment by Ekraam** [comment]
I have added the image urls for downloading in two separate files:

manipulated_image_urls.txt (train/test/val images) and 
reference_image_urls.txt (reference images)
